### ISSUE TITLE
Not able to create dynamic modules

### ISSUE THREAD

**Issue by JoseJavierMontero** [thierryc/grunt-handlebars-layouts#10]
Want to add same module twice but with different content:

**page.html**
// Defining dynamic content
```
{{#append "content1"}}
    Foo 
{{/append}}
{{#append "content2"}}
    Bar
{{/append}}
```

// Adding external partials
```
{{> my-module content="content1"}}
{{> my-module content="content2"}}
```

**my-module.html**
// Defining the module
```
<div class="my-module">
    {{#block "{{#content}}{{.}}{{/content}}" }}
    // Dynamic content to be placed here
    {{/block}}
</div>
```

Previous example is not working since block name inside " " cannot be dynamic.

**Comment by thierryc** [comment]
let me take a look...

**Comment by thierryc** [comment]
I do not try your exemple yet but i have create a new branch to update to handlebars 4.0. 
Can you try to fork and add your exemple in example directory on the banch ?

Best regards

**Comment by thierryc** [comment]
I have added __filename to the page context. __filename is the src filename. You can use it to create a dynamic content in to you files.

**Comment by thierryc** [comment]
you can add dynamic in your context : 

{
 "contentA": "foo",
 "contentB": "bar"
}

and use it in you page.
