### ISSUE TITLE
Upgrade to Handelbars 4

### ISSUE THREAD

**Issue by alexmaughan** [thierryc/grunt-handlebars-layouts#14]
Would it be possible to update your package to use Handlebars 4? It brings with it some nice new features, like partial blocks `{{> @partial-block }}`.

I did a quick test by updating handlebars to the following:

```
"handlebars": "~4.0.5"
```

...and it works fine with latest features.

**Comment by thierryc** [comment]
Good news ! Thank you.

**Comment by thierryc** [comment]
https://github.com/thierryc/grunt-handlebars-layouts/pull/16

I do
