### ISSUE TITLE
Issue with this + connect + watch

### ISSUE THREAD

**Issue by lonekorean** [thierryc/grunt-handlebars-layouts#2]
First, thanks for writing this. There's just one problem I'm stuck on.

The end of my grunt file looks like this:

```javascript
grunt.registerTask('run', [
  'build',
  'connect',
  'watch'
]);
```

'build" runs handlebarslayout within. When it executes, everything runs as expected, but right after 'connect', the command prompt returns. Grunt doesn't wait and watch. When I comment out the handlebarslayout task, it runs and waits/watches.

I'm not sure what's going on, so I'm asking here. Is there something about handlebarslayout that would break the usual connect/watch stuff? Some sort of async or early termination or something? Just guessing, I have no idea. :)

**Comment by thierryc** [comment]
It is a bug related to async. Is assigned to my self.

**Comment by thierryc** [comment]
it fixed... you have example in example/Gruntfile.js file

**Comment by lonekorean** [comment]
Thanks!
