### ISSUE TITLE
Warning: glob pattern string required

### ISSUE THREAD

**Issue by neagle** [thierryc/grunt-handlebars-layouts#8]
I have this context as an option in one of my handlebarslayouts tasks:

```
context: [
  'somepath/index.json',
  { buildTimestamp: buildTimestamp }
]
```

When I run the task, I get the error "Warning: glob pattern string required".

I traced the error to [line 255](https://github.com/thierryc/grunt-handlebars-layouts/blob/master/tasks/grunt-handlebars-layouts.js#L255) of `grunt-handlebars-layouts.js`, where it seems to happen when it tries to `resolve` an element that isn't a string (ie, a regular javascript object).

It looks like your documentation states pretty clearly that context should be able to contain mixed types. Am I doing something wrong, or is it possible there's just a missing check for type before trying to resolve items in a context array?

**Comment by thierryc** [comment]
What is: buildTimestamp type? 
Ca you tell me more about your grunt script? 

```
context: [
  'somepath/index.json',
  { buildTimestamp: 'sting' }
]

```
Can you try to replace buildTimestamp with a string? Just for tests.

**Comment by neagle** [comment]
Yeah, that was the first thing I thought to check, too. It's a string, and if I replace the variable with `'foo'` as you suggested, the error seems unchanged.

Let me see if I can create the simplest possible reproduction project.

**Comment by thierryc** [comment]
I have found... 
You can't (for the moment) use this function like this

```
context: [
  'somepath/index.json',
  { buildTimestamp: buildTimestamp }
]

```

The resolve method is for files [https://github.com/jonschlinkert/resolve-dep](https://github.com/jonschlinkert/resolve-dep)

But your issue may be a good suggestion for an enhancement.
I add it to the list !

**Comment by neagle** [comment]
Phew: so I'm not crazy?

Yeah, I just was able to reproduce the issue in example2 in the repo, just by adding some data to the context configuration:

```
	context: [
		'src/pages/**/*.json',
		{
			buildTimestamp: 'foo'
		}
	]
```

But the documentation seems to [explicitly say](https://github.com/thierryc/grunt-handlebars-layouts/blob/master/README.md#optional-configuration-properties) this should be supported, with this particular example:

```
context: [
  'path/to/context.json',
  'path/to/another/context.json',
  { more: 'data' }
]
```

Anyway, thanks for looking into it!

**Comment by thierryc** [comment]
Let me try

**Comment by thierryc** [comment]
I fix it ! try the new version 0.2.5

**Comment by thierryc** [comment]
let me know

**Comment by neagle** [comment]
I'll check it out as soon as I get to work tomorrow: I really appreciate the quick fix! Thank you!

--
Nate Eagle

**Comment by thierryc** [comment]
Great !

**Comment by neagle** [comment]
The new version works great: and you published it on npm already, too! I can't thank you enough for checking out my problem so quickly and pushing a fix. It was a big help to me.

**Comment by thierryc** [comment]
Your Welcome
Thank you for your feedback.
